name: dataoke_sdk
description: A Taobao customer interface plug-in. The integrated data comes from Dataoke, Zetaoke, Taobao Union SDK, Pinduoduo SDK, JINGdong SDK.
version: 2.0.0
homepage: https://github.com/mdddj/dataoke_sdk

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dio: ^4.0.6
  get: ^4.6.5
  logger: ^1.1.0
  hive: ^2.2.3
  hive_flutter: any
  dd_js_util: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive_generator: any
  build_runner: any

flutter:

  plugin:
    platforms:
      android:
        package: shop.itbug.dataoke_sdk
        pluginClass: DataokeSdkPlugin
      ios:
        pluginClass: DataokeSdkPlugin


