name: dataoke_sdk
description: A Taobao customer interface plug-in. The integrated data comes from Dataoke, Zetaoke, Taobao Union SDK, Pinduoduo SDK, JINGdong SDK.
version: 2.3.1
homepage: https://github.com/mdddj/dataoke_sdk

environment:
  sdk: ">=2.19.4 <3.0.0"
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dd_js_util: ^3.4.0
  freezed_annotation: ^2.2.0
  fast_immutable_collections: ^9.0.0
  dd_models: ^0.0.3

dev_dependencies:
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2


flutter:

  plugin:
    platforms:
      android:
        package: shop.itbug.dataoke_sdk
        pluginClass: DataokeSdkPlugin
      ios:
        pluginClass: DataokeSdkPlugin


