name: dataoke_sdk
description: A Taobao customer interface plug-in. The integrated data comes from Dataoke, Zetaoke, Taobao Union SDK, Pinduoduo SDK, JINGdong SDK.
version: 1.0.1
homepage: https://github.com/mdddj/dataoke_sdk

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  dio: ^4.0.6
  get: ^4.6.5
  logger: ^1.1.0
  dd_js_util:
    path: ../../dd_js_util

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  plugin:
    platforms:
      android:
        package: shop.itbug.dataoke_sdk
        pluginClass: DataokeSdkPlugin
      ios:
        pluginClass: DataokeSdkPlugin


