name: dataoke_sdk
description: A Taobao customer interface plug-in. The integrated data comes from Dataoke, Zetaoke, Taobao Union SDK, Pinduoduo SDK, JINGdong SDK.
version: 4.0.9
homepage: https://github.com/mdddj/dataoke_sdk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.0.2+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dd_js_util: ^6.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  fast_immutable_collections: ^10.1.0
  dd_models: ^0.1.0
  dio: ^5.4.0


dev_dependencies:
  hive_generator_plus: ^3.0.4
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  freezed: ^2.4.7
  flutter_lints: ^3.0.1

dependency_overrides:
  watcher: ^1.1.0
  meta: ^1.11.0

flutter:

  plugin:
    platforms:
      android:
        package: shop.itbug.dataoke_sdk
        pluginClass: DataokeSdkPlugin
      ios:
        pluginClass: DataokeSdkPlugin


