name: dd_models
description: diandian de model with flutter plugin
version: 0.0.3
homepage: https://github.com/mdddj/dataoke_sdk

environment:
  sdk: '>=2.17.4 <3.0.0'
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  plugin_platform_interface: ^2.1.4
  fast_immutable_collections: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1



flutter:
  plugin:
    platforms:
      android:
        package: shop.itbug.dd_models
        pluginClass: DdModelsPlugin
      ios:
        pluginClass: DdModelsPlugin
      linux:
        pluginClass: DdModelsPlugin
      macos:
        pluginClass: DdModelsPlugin
      windows:
        pluginClass: DdModelsPluginCApi
      web:
        pluginClass: DdModelsWeb
        fileName: dd_models_web.dart