name: dd_models
description: diandian de model with flutter plugin
version: 0.1.0
homepage: https://github.com/mdddj/dataoke_sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.1.8
  fast_immutable_collections: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1


dependency_overrides:
  watcher: ^1.1.0

flutter:
  plugin:
    platforms:
      android:
        package: shop.itbug.dd_models
        pluginClass: DdModelsPlugin
      ios:
        pluginClass: DdModelsPlugin
      linux:
        pluginClass: DdModelsPlugin
      macos:
        pluginClass: DdModelsPlugin
      windows:
        pluginClass: DdModelsPluginCApi
      web:
        pluginClass: DdModelsWeb
        fileName: dd_models_web.dart